In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
project_name='python-practice-assignment'

In [4]:
# Capture and upload a snapshot
jovian.commit(project=project_name, privacy='secret', evironment=None)

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Creating a new project "rakesh-rajagopalachary/python-practice-assignment"
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment'

In [6]:
name = 'Rakesh'

In [7]:
age = "30"

In [8]:
has_android_phone = "Yes"

In [9]:
name, age, has_android_phone

('Rakesh', '30', 'Yes')

In [17]:
person = {
    "Name":"Rakesh",
    "Age": 30,
    "HasAndroidPhone" : "Yes"
}

In [18]:
print("{} is aged {}, and owns an {}.".format(
    person["Name"], 
    person["Age"], 
    "Android phone" if person["HasAndroidPhone"] else "iPhone"
))

Rakesh is aged 30, and owns an Android phone.


In [19]:
jovian.commit(project=project_name,environment=None)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-practice-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment'

In [25]:
my_list = ['Blue', '2', '1']

In [21]:
my_list

['Blue', '2', '1']

In [26]:
my_list.pop(0)

'Blue'

In [27]:
my_list

['2', '1']

In [33]:
print("The list has {} elements.".format(my_list))

The list has ['2', '1'] elements.


In [34]:
jovian.commit(project=project_name,environment=None)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-practice-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment'

In [87]:
%%time
sum_of_numbers =0
for i in range(18,534):
    if i%7 == 0:
           sum_of_numbers += i   
print('The sum of all the numbers divisible by 7 between 18 and 534 is: {}'.format(sum_of_numbers))

The sum of all the numbers divisible by 7 between 18 and 534 is: 20461
Wall time: 0 ns


In [ ]:
jovian.commit(project=project_name,environment=None)

<IPython.core.display.Javascript object>

In [79]:
result

423289965

In [68]:
t = t + i
t

42

In [45]:
result = result + i
result

4567990417

In [1]:
jovian.commit(project=project_name,environment=None)

NameError: name 'project_name' is not defined

In [2]:
# Import it
import jovian

In [3]:
project_name='python-practice-assignment'

In [4]:
# Capture and upload a snapshot
jovian.commit(project=project_name, privacy='secret', evironment=None)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-practice-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment'

In [5]:
cost_of_flying_plane = 5000

In [17]:
number_of_passengers = 29

In [18]:
price_of_ticket = 200

In [19]:
profit = (number_of_passengers * price_of_ticket) - cost_of_flying_plane
print('The company makes of a profit of {} dollars'.format(profit))

The company makes of a profit of 800 dollars


In [20]:
cost_of_flying_plane = 5000

In [21]:
number_of_passengers = 12

In [22]:
price_of_ticket = 200

In [23]:
profit = (number_of_passengers * price_of_ticket) - cost_of_flying_plane
# this is optional
if profit >= 0:
    print("The company makes an overall profit of {} dollars".format(profit))
else:
    print("The company makes an overall loss of {} dollars".format(profit))

The company makes an overall loss of -2600 dollars


In [24]:
jovian.commit(project=project_name,environment=None)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-practice-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment'

In [25]:
!pip install numpy --upgrade --quiet

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.22.3 which is incompatible.


In [26]:
!pip install numpy

In [27]:
import numpy as np

In [7]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [11]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [15]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

261.4

In [4]:
w1

0.3

In [5]:
w2

0.2

In [14]:
kanto_temp, kanto_rainfall, kanto_humidity = 755, 67, 43

In [16]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 261.4 tons per hectare.


In [32]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [18]:
kanto

[73, 67, 43]

In [33]:
weights = [w1, w2, w3]

In [20]:
weights = (w1, w2, w3)

In [21]:
weights = [w1, w2, 3]

In [22]:
weights = (w1, w2, 3)

In [23]:
weights = [w1, w2, w3]

In [36]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [37]:
crop_yield(kanto, weights)

56.8

In [38]:
import numpy as np

In [39]:
kanto = np.array([73, 67, 43])

In [40]:
kanto

array([73, 67, 43])

In [41]:
weights = np.array([w1, w2, w3])

In [42]:
weights

array([0.3, 0.2, 0.5])

In [43]:
type(weights)

numpy.ndarray

In [44]:
weights[0]

0.3

In [46]:
weights[2]

0.5

In [47]:
kanto[2]

43

In [48]:
np.dot(kanto, weights)

56.8

In [49]:
(kanto*weights).sum()

56.8

In [50]:
(kanto*weights)

array([21.9, 13.4, 21.5])

In [51]:
(kanto*weights).mean()

18.933333333333334

In [53]:
(21.9+13.4+21.5)

56.8

In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [55]:
arr1 * arr2

array([ 4, 10, 18])

In [56]:
arr2.sum()

15

In [57]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [58]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

Wall time: 2.29 s


833332333333500000

In [59]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 8 ms


-1942957984

In [60]:
import jovian

In [61]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-practice-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-practice-assignment'

In [62]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [63]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [64]:
climate_data = ([[73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]])

In [65]:
climate_data

[[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]]

In [66]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [67]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [68]:
weights

array([0.3, 0.2, 0.5])

In [69]:
# 1D array (vector)
weights.shape

(3,)

In [70]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [71]:
arr3.shape

(2, 2, 3)

In [72]:
arr3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [73]:
weights.dtype

dtype('float64')

In [74]:
climate_data.dtype

dtype('int32')

In [75]:
arr3.dtype

dtype('float64')

In [76]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [81]:
t = (climate_data*weights)
t

array([[21.9, 13.4, 21.5],
       [27.3, 17.6, 32. ],
       [26.1, 26.8, 29. ],
       [30.6,  8.6, 18.5],
       [20.7, 19.2, 35. ]])

In [80]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [82]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1b8fa95b370>)

In [83]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [84]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [85]:
climate_data.shape

(10000, 3)

In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\admin'

In [3]:
help(os.listdir)

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [4]:
os.listdir('.') # relative path

['.ipynb_checkpoints',
 '.ipython',
 '.jovian',
 '.jovianrc',
 '.jupyter',
 '.spyder-py3',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'climate.txt',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'JOVIAN.ipynb',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled4.ipynb',
 'Videos']

In [5]:
os.listdir('/usr') # absolute path

FileNotFoundError: [WinError 3] The system cannot find the path specified: '/usr'

In [6]:
os.makedirs('./data', exist_ok=True)

In [7]:
'data' in os.listdir('.')

True

In [8]:
url1 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'
url2 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans2.txt'
url3 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans3.txt'

In [9]:
url1

'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'

In [11]:
from urllib.request import urlretrieve

In [12]:
urlretrieve(url1, './data/loans1.txt')

('./data/loans1.txt', <http.client.HTTPMessage at 0x217a86ac640>)

In [13]:
url1

'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'

In [14]:
urlretrieve(url2, './data/loans1.txt')

('./data/loans1.txt', <http.client.HTTPMessage at 0x217a831e760>)

In [15]:
urlretrieve(url3, './data/loans1.txt')

('./data/loans1.txt', <http.client.HTTPMessage at 0x217a83227f0>)

In [16]:
os.listdir('./data')

['loans1.txt']

In [1]:
!pip install jovian --upgrade --quiet

In [1]:
import jovian

In [2]:
jovian.commit(project='python-sudoku-solver-assignment', privacy='secret')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-sudoku-solver-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment'

In [3]:
puzzle1 = [[5, 3, 0, 0, 7, 0, 0, 0, 0], 
           [6, 0, 0, 1, 9, 5, 0, 0, 0], 
           [0, 9, 8, 0, 0, 0, 0, 6, 0], 
           [8, 0, 0, 0, 6, 0, 0, 0, 3],
           [4, 0, 0, 8, 0, 3, 0, 0, 1],
           [7, 0, 0, 0, 2, 0, 0, 0, 6],
           [0, 6, 0, 0, 0, 0, 2, 8, 0],
           [0, 0, 0, 4, 1, 9, 0, 0, 5],
           [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [9]:
print(puzzle1)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [4]:
import numpy as np

In [5]:
print(np.matrix(puzzle1))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [8]:
puzzle1

[[5, 3, 0, 0, 7, 0, 0, 0, 0],
 [6, 0, 0, 1, 9, 5, 0, 0, 0],
 [0, 9, 8, 0, 0, 0, 0, 6, 0],
 [8, 0, 0, 0, 6, 0, 0, 0, 3],
 [4, 0, 0, 8, 0, 3, 0, 0, 1],
 [7, 0, 0, 0, 2, 0, 0, 0, 6],
 [0, 6, 0, 0, 0, 0, 2, 8, 0],
 [0, 0, 0, 4, 1, 9, 0, 0, 5],
 [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [20]:
def possible (y,x,n):
    global puzzle1
    for i in range (0,9):
        if puzzle1[y][i]==n:
            return False
    for i in range (0,9):
        if puzzle1[i][x]==n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range (0,3):
        for j in range (0,3):
            if puzzle1[y0+i][x0+j]==n:
                return False
    return True

In [24]:
def solve ():
    global puzzle1
    for y in range (9):
        for x in range (9):
            if puzzle1[y][x] == 0:
                for n in range (1,10):
                    if possible(y,x,n):
                        puzzle1[y][x]=n
                        solve()
                        puzzle1[y][x] = 0
                return
    print(np.matrix(puzzle1))
    print ("done")

In [25]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
done


In [26]:
global puzzle1

In [27]:
puzzle1

[[5, 3, 4, 6, 7, 8, 9, 1, 2],
 [6, 7, 2, 1, 9, 5, 3, 4, 8],
 [1, 9, 8, 3, 4, 2, 5, 6, 7],
 [8, 5, 9, 7, 6, 1, 4, 2, 3],
 [4, 2, 6, 8, 5, 3, 7, 9, 1],
 [7, 1, 3, 9, 2, 4, 8, 5, 6],
 [9, 6, 1, 5, 3, 7, 2, 8, 4],
 [2, 8, 7, 4, 1, 9, 6, 3, 5],
 [3, 4, 5, 2, 8, 6, 1, 7, 9]]

In [28]:
puzzle1 = [[5, 3, 0, 0, 7, 0, 0, 0, 0], 
           [6, 0, 0, 1, 9, 5, 0, 0, 0], 
           [0, 9, 8, 0, 0, 0, 0, 6, 0], 
           [8, 0, 0, 0, 6, 0, 0, 0, 3],
           [4, 0, 0, 8, 0, 3, 0, 0, 1],
           [7, 0, 0, 0, 2, 0, 0, 0, 6],
           [0, 6, 0, 0, 0, 0, 2, 8, 0],
           [0, 0, 0, 4, 1, 9, 0, 0, 5],
           [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [29]:
puzzle1

[[5, 3, 0, 0, 7, 0, 0, 0, 0],
 [6, 0, 0, 1, 9, 5, 0, 0, 0],
 [0, 9, 8, 0, 0, 0, 0, 6, 0],
 [8, 0, 0, 0, 6, 0, 0, 0, 3],
 [4, 0, 0, 8, 0, 3, 0, 0, 1],
 [7, 0, 0, 0, 2, 0, 0, 0, 6],
 [0, 6, 0, 0, 0, 0, 2, 8, 0],
 [0, 0, 0, 4, 1, 9, 0, 0, 5],
 [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [30]:
# Number of rows
len(puzzle1)

9

In [31]:
# Number of elements row no. 0
len(puzzle1[0])

9

In [32]:
# Row no. 0
puzzle1[0]

[5, 3, 0, 0, 7, 0, 0, 0, 0]

In [33]:
# Element at Row no. 2 and col no. 2 (counting from 0)
puzzle1[2][2]

8

In [34]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-sudoku-solver-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment'

In [6]:
solution1 = [[5, 3, 4, 6, 7, 8, 9, 1, 2],
             [6, 7, 2, 1, 9, 5, 3, 4, 8],
             [1, 9, 8, 3, 4, 2, 5, 6, 7],
             [8, 5, 9, 7, 6, 1, 4, 2, 3],
             [4, 2, 6, 8, 5, 3, 7, 9, 1],
             [7, 1, 3, 9, 2, 4, 8, 5, 6],
             [9, 6, 1, 5, 3, 7, 2, 8, 4],
             [2, 8, 7, 4, 1, 9, 6, 3, 5],
             [3, 4, 5, 2, 8, 6, 1, 7, 9]]

In [7]:
solution1

[[5, 3, 4, 6, 7, 8, 9, 1, 2],
 [6, 7, 2, 1, 9, 5, 3, 4, 8],
 [1, 9, 8, 3, 4, 2, 5, 6, 7],
 [8, 5, 9, 7, 6, 1, 4, 2, 3],
 [4, 2, 6, 8, 5, 3, 7, 9, 1],
 [7, 1, 3, 9, 2, 4, 8, 5, 6],
 [9, 6, 1, 5, 3, 7, 2, 8, 4],
 [2, 8, 7, 4, 1, 9, 6, 3, 5],
 [3, 4, 5, 2, 8, 6, 1, 7, 9]]

In [37]:
len(solution1) == 9 and len(solution1[0]) == 9

True

In [38]:
row3 = solution1[3]

In [39]:
row3

[8, 5, 9, 7, 6, 1, 4, 2, 3]

In [40]:
row3 == [8, 5, 9, 7, 6, 1, 4, 2, 3]

True

In [41]:
val_4_5 = solution1[4][5]

In [42]:
val_4_5

3

In [43]:
val_4_5 == 3

True

In [46]:
val_last_zero = solution1[8][0]

In [47]:
val_last_zero

3

In [48]:
val_last_zero == 3

True

In [49]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-sudoku-solver-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment'

IndentationError: expected an indented block (Temp/ipykernel_13716/1378668931.py, line 3)

In [22]:
solution1 = [[5, 3, 4, 6, 7, 8, 9, 1, 2],
             [6, 7, 2, 1, 9, 5, 3, 4, 8],
             [1, 9, 8, 3, 4, 2, 5, 6, 7],
             [8, 5, 9, 7, 6, 1, 4, 2, 3],
             [4, 2, 6, 8, 5, 3, 7, 9, 1],
             [7, 1, 3, 9, 2, 4, 8, 5, 6],
             [9, 6, 1, 5, 3, 7, 2, 8, 4],
             [2, 8, 7, 4, 1, 9, 6, 3, 5],
             [3, 4, 5, 2, 8, 6, 1, 7, 9]]

In [23]:
puzzle1 = [[5, 3, 0, 0, 7, 0, 0, 0, 0], 
           [6, 0, 0, 1, 9, 5, 0, 0, 0], 
           [0, 9, 8, 0, 0, 0, 0, 6, 0], 
           [8, 0, 0, 0, 6, 0, 0, 0, 3],
           [4, 0, 0, 8, 0, 3, 0, 0, 1],
           [7, 0, 0, 0, 2, 0, 0, 0, 6],
           [0, 6, 0, 0, 0, 0, 2, 8, 0],
           [0, 0, 0, 4, 1, 9, 0, 0, 5],
           [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [24]:
def get_row(sudoku,k):
    return sudoku[k]

In [25]:
get_row(puzzle1,2)

[0, 9, 8, 0, 0, 0, 0, 6, 0]

In [26]:
get_row(solution1, 3)

[8, 5, 9, 7, 6, 1, 4, 2, 3]

In [27]:
get_row(solution1, 3) == [8, 5, 9, 7, 6, 1, 4, 2, 3]

True

In [28]:
def get_col(sudoku, k):
    result =[]
    for i in range(0,9):
        result.append (sudoku[i][k])
    return result
    

In [29]:
get_col(puzzle1, 4)

[7, 9, 0, 6, 0, 2, 0, 1, 8]

In [30]:
get_col(solution1, 5)

[8, 5, 2, 1, 3, 4, 7, 9, 6]

In [31]:
get_col(solution1, 5) == [8, 5, 2, 1, 3, 4, 7, 9, 6]

True

In [36]:
def get_box(sudoku, k):
    if k == 0:
        return sudoku [0][0:3] + sudoku [1][0:3] + sudoku [2][0:3]
    elif k == 1:
        return sudoku [0][3:6] + sudoku [1][3:6] + sudoku [2][3:6]
    elif k == 2:
        return sudoku [0][6:9] + sudoku [1][6:9] + sudoku [2][6:9]
    elif k == 3:
        return sudoku [3][0:3] + sudoku [4][0:3] + sudoku [5][0:3]
    elif k == 4:
        return sudoku [3][3:6] + sudoku [4][3:6] + sudoku [5][3:6]
    elif k == 5:
        return sudoku [3][6:9] + sudoku [4][6:9] + sudoku [5][6:9]
    elif k == 6:
        return sudoku [6][0:3] + sudoku [7][0:3] + sudoku [8][0:3]
    elif k == 7:
        return sudoku [6][3:6] + sudoku [7][3:6] + sudoku [8][3:6]
    elif k == 8:
        return sudoku [6][6:9] + sudoku [7][6:9] + sudoku [8][6:9]
    

In [37]:
get_box(puzzle1, 0)

[5, 3, 0, 6, 0, 0, 0, 9, 8]

In [38]:
get_box(solution1, 7)

[5, 3, 7, 4, 1, 9, 2, 8, 6]

In [39]:
get_box(solution1, 7) == [5, 3, 7, 4, 1, 9, 2, 8, 6]

True

In [8]:
def first_empty_position(sudoku):
    for i in range (9):
        for j in range (9):
            if sudoku [i][j] == 0:
                return i,j
    return None, None

In [9]:
first_empty_position(puzzle1)

(0, 2)

In [10]:
first_empty_position(solution1)

(None, None)

In [11]:
first_empty_position(puzzle1) == (0, 2)

True

In [12]:
first_empty_position(solution1) == (None, None)

True

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-sudoku-solver-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment'

In [14]:
def is_section_valid(nums):
    for digit in range (1, 10):
        if nums.count(digit)>1:
            return False
    return True

In [15]:
# should return True
is_section_valid([5, 3, 7, 4, 1, 9, 2, 8, 6])

True

In [16]:
# should return True
is_section_valid([5, 3, 0, 6, 0, 0, 0, 9, 8])

True

In [17]:
# should return False
is_section_valid([5, 3, 0, 6, 0, 8, 0, 9, 8])

False

In [40]:
def is_sudoku_valid(sudoku):
    rows_valid = all([is_section_valid(get_row(sudoku, i)) for i in range(0, 9)])
    cols_valid = all([is_section_valid(get_col(sudoku, i)) for i in range(0, 9)])
    boxes_valid = all([is_section_valid(get_box(sudoku, i)) for i in range(0, 9)])
    return rows_valid and cols_valid and boxes_valid

In [41]:
# Valid Puzzle
puzzle2 = [[5, 3, 0, 0, 7, 0, 0, 0, 0], 
           [6, 0, 0, 1, 9, 5, 0, 0, 0], 
           [0, 9, 8, 0, 4, 0, 0, 6, 0], 
           [8, 0, 0, 0, 6, 0, 0, 0, 3],
           [4, 0, 0, 8, 0, 3, 0, 0, 1],
           [7, 0, 0, 0, 2, 0, 0, 0, 6],
           [0, 6, 0, 0, 0, 0, 2, 8, 0],
           [0, 0, 0, 4, 1, 9, 0, 0, 5],
           [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [42]:
# Invalid Puzzle
puzzle2 = [[5, 3, 0, 0, 7, 0, 0, 0, 0], 
           [6, 0, 0, 1, 9, 5, 0, 0, 0], 
           [0, 9, 8, 0, 8, 0, 0, 6, 0], 
           [8, 0, 0, 0, 6, 0, 0, 0, 3],
           [4, 0, 0, 8, 0, 3, 0, 0, 1],
           [7, 0, 0, 0, 2, 0, 0, 0, 6],
           [0, 6, 0, 0, 0, 0, 2, 8, 0],
           [0, 0, 0, 4, 1, 9, 0, 0, 5],
           [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [43]:
# should return True
is_sudoku_valid(puzzle1)

True

In [44]:
# should return False
is_sudoku_valid(puzzle2)

False

In [45]:
def is_section_complete(nums):
    for digit in range (1,10):
        if nums.count (digit) !=1:
            return False
    return True

In [46]:
# should return False
is_section_complete([0, 9, 8, 0, 0, 0, 0, 6, 0])

False

In [47]:
# should return True
is_section_complete([1, 9, 8, 3, 4, 2, 5, 6, 7])

True

In [48]:
def is_sudoku_complete(sudoku):
    rows_complete = all([is_section_complete(get_row(sudoku, i)) for i in range(0, 9)])
    cols_complete = all([is_section_complete(get_col(sudoku, i)) for i in range(0, 9)])
    boxes_complete = all([is_section_complete(get_box(sudoku, i)) for i in range(0, 9)])
    return rows_complete and cols_complete and boxes_complete

In [49]:
# should return False
is_sudoku_complete(puzzle1)

False

In [50]:
# should return True
is_sudoku_complete(solution1)

True

In [51]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "rakesh-rajagopalachary/python-sudoku-solver-assignment" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment


'https://jovian.ai/rakesh-rajagopalachary/python-sudoku-solver-assignment'